// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.21 - 15.20-s010_1
tclmode
set env(RC_VERSION) "GENUS15.21 - 15.20-s010_1"
vpxmode
set dofile abort exit
usage -auto -elapse
set log file logs/rtl2intermediate.lec.log -replace
tclmode
set ver [lindex [split [lindex [get_version_info] 0] "-"] 0]
vpxmode
tclmode
set env(CDN_SYNTH_ROOT) /afs/ee.cooper.edu/dist/cadence/installs/genus/tools
set CDN_SYNTH_ROOT /afs/ee.cooper.edu/dist/cadence/installs/genus/tools
vpxmode
tclmode
if {$ver >= 08.10} {
  vpx set naming style rc
}
vpxmode
set naming rule "%s[%d]" -instance_array
set naming rule "%s_reg" -register -golden
set naming rule "%L.%s" "%L[%d].%s" "%s" -instance
set naming rule "%L.%s" "%L[%d].%s" "%s" -variable
set undefined cell black_box -noascend -both
set hdl options -VERILOG_INCLUDE_DIR "sep:src:cwd"
set undriven signal Z -golden

add search path -library . /afs/ee.cooper.edu/courses/ece447/gpdk/GPDK045/gsclib045_svt_v4.4/gsclib045
read library -statetable -liberty -both  \
	/afs/ee.cooper.edu/courses/ece447/gpdk/GPDK045/gsclib045_svt_v4.4/gsclib045/timing/slow_vdd1v0_basicCells.lib

delete search path -all
add search path -design ../../RTL/
tclmode
if {$ver < 13.10} {
vpx read design   -define SYNTHESIS -keep_unreach -golden -lastmod -noelab -verilog2k \
	../../RTL/DSP.v
} else {
vpx read design   -define SYNTHESIS -keep_unreach -merge bbox -golden -lastmod -noelab -verilog2k \
	../../RTL/DSP.v
}
vpxmode

elaborate design -golden -root DSP -rootonly

tclmode
if {$ver < 13.10} {
vpx read design -verilog -revised -lastmod -noelab \
	outputs/DSP_intermediate.v
} else {
vpx read design -verilog95 -revised -lastmod -noelab \
	outputs/DSP_intermediate.v
}
vpxmode

elaborate design -revised -root DSP

tclmode
set ver [lindex [split [lindex [get_version_info] 0] "-"] 0]
if {$ver < 13.10} {
vpx substitute blackbox model -golden
}
vpxmode
report design data
report black box

uniquify -all -nolib
set flatten model -seq_constant -seq_constant_x_to 0
set flatten model -nodff_to_dlat_zero -nodff_to_dlat_feedback
set parallel option -threads 4 -license xl -norelease_license
set flatten model -gated_clock
set analyze option -auto

write hier_compare dofile outputs/hier_rtl2intermediate.lec.do \
	-noexact_pin_match -constraint -usage -replace -balanced_extraction -input_output_pin_equivalence \
	-prepend_string "analyze datapath -module -verbose ; usage; analyze datapath  -verbose"
run hier_compare outputs/hier_rtl2intermediate.lec.do -dynamic_hierarchy
// report hier_compare result -dynamicflattened
set system mode lec
tclmode
puts "No of diff points    = [get_compare_points -NONequivalent -count]"
if {[get_compare_points -NONequivalent -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
#     foreach i [get_compare_points -NONequivalent] {
#         vpx report test vector [get_keypoint $i]
#         puts "     ----------------------------"
#     }
}
vpxmode
exit -force
