// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.21 - 15.20-s010_1
tclmode
set env(RC_VERSION) "GENUS15.21 - 15.20-s010_1"
vpxmode
set dofile abort exit
usage -auto -elapse
set log file logs_Apr07-13:24:47/intermediate2final.lec.log -replace
tclmode
set ver [lindex [split [lindex [get_version_info] 0] "-"] 0]
vpxmode
tclmode
set env(CDN_SYNTH_ROOT) /afs/ee.cooper.edu/dist/cadence/installs/genus/tools
set CDN_SYNTH_ROOT /afs/ee.cooper.edu/dist/cadence/installs/genus/tools
vpxmode
set undefined cell black_box -noascend -both
set hdl options -VERILOG_INCLUDE_DIR "sep:src:cwd"

add search path -library . /afs/ee.cooper.edu/courses/ece447/gpdk/GPDK045/gsclib045_svt_v4.4/gsclib045
read library -statetable -liberty -both  \
	/afs/ee.cooper.edu/courses/ece447/gpdk/GPDK045/gsclib045_svt_v4.4/gsclib045/timing/slow_vdd1v0_basicCells.lib

tclmode
if {$ver < 13.10} {
vpx read design -verilog -golden -lastmod -noelab \
	outputs_Apr07-13:24:47/DSPFetch_intermediate.v
} else {
vpx read design -verilog95 -golden -lastmod -noelab \
	outputs_Apr07-13:24:47/DSPFetch_intermediate.v
}
vpxmode

elaborate design -golden -root DSPFetch

tclmode
if {$ver < 13.10} {
vpx read design -verilog -revised -lastmod -noelab \
	outputs_Apr07-13:24:47/DSPFetch_m.v
} else {
vpx read design -verilog95 -revised -lastmod -noelab \
	outputs_Apr07-13:24:47/DSPFetch_m.v
}
vpxmode

elaborate design -revised -root DSPFetch

tclmode
set ver [lindex [split [lindex [get_version_info] 0] "-"] 0]
if {$ver < 13.10} {
vpx substitute blackbox model -golden
}
vpxmode
report design data
report black box

uniquify -all -nolib
set flatten model -seq_constant -seq_constant_x_to 0
set flatten model -nodff_to_dlat_zero -nodff_to_dlat_feedback
set parallel option -threads 4 -license xl -norelease_license
set analyze option -auto

set system mode lec
// report mapped points
report unmapped points -summary
report unmapped points -extra -unreachable -notmapped
add compared points -all
// report compared points
compare
usage
// report compare data
report compare data -class nonequivalent -class abort -class notcompared
report verification -verbose
report statistics
tclmode
puts "No of compare points = [get_compare_points -count]"
puts "No of diff points    = [get_compare_points -NONequivalent -count]"
puts "No of abort points   = [get_compare_points -abort -count]"
puts "No of unknown points = [get_compare_points -unknown -count]"
if {[get_compare_points -count] == 0} {
    puts "---------------------------------"
    puts "ERROR: No compare points detected"
    puts "---------------------------------"
}
if {[get_compare_points -NONequivalent -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
#     foreach i [get_compare_points -NONequivalent] {
#         vpx report test vector [get_keypoint $i]
#         puts "     ----------------------------"
#     }
}
if {[get_compare_points -abort -count] > 0} {
    puts "-----------------------------"
    puts "ERROR: Abort Points detected "
    puts "-----------------------------"
}
if {[get_compare_points -unknown -count] > 0} {
    puts "----------------------------------"
    puts "ERROR: Unknown Key Points detected"
    puts "----------------------------------"
}
vpxmode
exit -force
